Make password optional
vapor/mysql-driver pull request #196
Opened 2020-08-23 16:08 UTC by Lloople

I'm very new to both Swift and Vapor, but I'm trying my best here so sorry about any possible mistake 🙏.

I tried to add a test for this scenario but I don't know enough yet 😅.

This fixes #195 . I don't have a password on my local environment for the MySQL user and I was unable to run migrations, this is why I think this change should be addressed. 

Thank you for your time and framework.

2020-08-24 08:32 UTC, 0xTim commented
I suspect this will need to be fixed in MySQL-Kit first before being added to Fluent. I think passing an empty string is not the same as passing nothing, but it depends on how MySQL works. I'm going to hook @gwynne in here as she's done a ton of work on MySQL auth recently

2020-08-24 21:57 UTC, gwynne commented
Had to test this to be sure, but it turns out that no additional effort at the MySQLKit or MySQLNIO layer is required - in MySQL, "no password" and "the password is an empty string" are the same thing.

I will post a review with further comments.

2020-08-24 22:17 UTC, gwynne requested changes
Unfortunately, making the password parameter an `Optional` is technically API-breaking, as certain usages will not be source-compatible. _However_, this feels like one of those situations similar to the "adding cases to an `enum`" problem where requiring semver-major for something that will not affect 99.9% of users feels excessive, and an exception to make it semver-minor instead seems reasonable. As such, I will defer to @tanner0101's judgement with regards to the semver issue.

More concerning to me is that #195 shows an error being returned with "using password: YES" as part of the message even in the presence of an empty string, even though I have just successfully tested this using an identical configuration locally. It turns out that while this works fine with MySQL 8.0, it does _not_ work with MySQL 5.7. I will have to investigate further.

2020-08-24 22:17 UTC, gwynne commented on Sources/FluentMySQLDriver/FluentMySQLConfiguration.swift
> +        password: String? = nil,
```suggestion
        password: String?,
```

Do not default the password to nil - we don't want to encourage use of empty passwords.

2020-08-24 22:17 UTC, gwynne commented on Sources/FluentMySQLDriver/FluentMySQLConfiguration.swift
> +        password: String? = nil,
```suggestion
        password: String?,
```
Again, don't default to `nil`

2020-08-25 00:01 UTC, gwynne commented
On further investigation, the difference between 5.7 and 8.0 turns out to be due to 8.0 using `caching_sha2_password` as the default instead of `mysql_native_password`. The bug here is actually at the MySQLNIO layer, which incorrectly encodes a complete auth response for an empty password `""`, when the correct behavior for the `mysql_native_password` plugin is to encode no auth response at all in that case. The existing behavior is already correct for the caching SHA-2 plugin.

As such, this PR is unnecessary; I am closing it out in favor of the one I'm about to open against MySQLNIO. @Lloople Your effort and contributions are very much appreciated, and my closing this PR out is in no way intended to discourage you! Please don't hesitate to open new issues and PRs in the future; they are always welcome- this one definitely served to point me in the right direction to fix the problem!

2020-08-25 00:01 UTC, closed without merging

2020-08-25 06:26 UTC, Lloople commented
Thank you very much for your time and for such an explanation about the issue! 😍  I'll try my best to continue helping with anything I can