Default field values (WIP)
vapor/mysql-driver pull request #59
Opened 2018-01-16 23:53 UTC by rafiki270

Adding support for default values for `ColumnType`s

Please let me know if this is something you would consider merging in given it would have all the missing comments and tests.

2018-01-17 00:11 UTC, rafiki270 commented
so after discussion with @tanner0101 I will try to add a `defaultValue: Encodable?` to the `public struct SchemaField<Database> where Database: SchemaSupporting` and try to make a foundation for all db's ... or I might create a feature request and ask some proper developer to do this

2018-01-22 09:12 UTC, tanner0101 commented
Keeping this open until the issue is resolved on Fluent. :)

2018-02-28 05:50 UTC, tanner0101 requested changes
We're trying to avoid public enums at all costs. Adding new cases is considered a breaking change.

2018-02-28 05:50 UTC, tanner0101 commented on Sources/FluentMySQL/DefaultValue.swift
> +public enum DefaultValue {
There should at least be a `raw` case here to pass a custom function. Event better, have `DefaultValue` be a struct and have all of the cases be static conveniences :)

Also, should be `MySQLDefaultValue` for namespacing

```swift
struct MySQLDefaultValue {
    public var value: String

    public static var null: MySQLDefaultValue { return .init(value: "NULL") }
    ... etc
}
```

2018-06-14 21:50 UTC, tanner0101 commented
This will be possible in version 3 by adding custom field types. 👍

2018-06-14 21:50 UTC, closed without merging